markdown: kramdown
highlighter: pygments
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

gauges_id: 503c5af6613f5d0f19000027
google_analytics_id: UA-50755011-1

repository: https://github.com/jekyll-brasil/jekyll-brasil.github.io
help_url: https://github.com/jekyll/jekyll-help

timezone: America/Brasilia

collections:
  docs:
    output: true

name: Jekyll • Simple, blog-aware, static sites
description: Transforme seu texto simples em sites estáticos e blogs.
url: http://jekyll-brasil.github.io

gems:
  - jekyll-feed
